#!/bin/bash -e

MILLIONAIRE=millionaire.cir
ALICE=test/alice
BOB=test/bob

mkdir -p results

echo "a $1" > test/alice
echo "b $2" > test/bob

java -ea -cp dist/GCParser.jar:extlibs/jargs.jar:extlibs/commons-io-1.4.jar Test.TestGCParserServer -f "$MILLIONAIRE" -p "$BOB" -w 80 > results/bob.out &
sleep 0.8
java -ea -cp dist/GCParser.jar:extlibs/jargs.jar:extlibs/commons-io-1.4.jar Test.TestGCParserClient -f "$MILLIONAIRE" --server localhost -r 1 -p "$ALICE" > results/alice.out &
