#!/bin/bash -e

MILLIONAIRE=millionaire.cir
ALICE=test/alice
BOB=test/bob

echo ".input a 1 $1
.input b 2 $1
yao gteu a b
.output yao" > "$MILLIONAIRE"

mkdir -p results

echo "a $2" > "$ALICE"
echo "b $3" > "$BOB"

java -ea -cp dist/GCParser.jar:extlibs/jargs.jar:extlibs/commons-io-1.4.jar Test.TestGCParserServer -f "$MILLIONAIRE" -p "$BOB" -w 80 > results/bob.out &
sleep 0.8
java -ea -cp dist/GCParser.jar:extlibs/jargs.jar:extlibs/commons-io-1.4.jar Test.TestGCParserClient -f "$MILLIONAIRE" --server localhost -r 1 -p "$ALICE" > results/alice.out &
