#!/bin/bash -e

DOTPRODUCT=tbaseddotprod.cir
ALICE=test/alice_vector
BOB=test/bob_vector

mkdir -p results

python -m dotproduct "$1" "$2" "$3"

java -ea -cp dist/GCParser.jar:extlibs/jargs.jar:extlibs/commons-io-1.4.jar Test.TestGCParserServer -f "$DOTPRODUCT" -p "$BOB" -w 80 > results/bob.out &
sleep 0.8
java -ea -cp dist/GCParser.jar:extlibs/jargs.jar:extlibs/commons-io-1.4.jar Test.TestGCParserClient -f "$DOTPRODUCT" --server localhost -r 1 -p "$ALICE" > results/alice.out &
